S390X_SRC=$(SRC_PATH)/tests/tcg/s390x
VPATH+=$(S390X_SRC)
QEMU_OPTS=-action panic=exit-failure -kernel
LINK_SCRIPT=$(S390X_SRC)/softmmu.ld
LDFLAGS=-nostdlib -static -Wl,-T$(LINK_SCRIPT) -Wl,--build-id=none

%.o: %.S
	$(CC) -march=z13 -m64 -c $< -o $@

%: %.o $(LINK_SCRIPT)
	$(CC) $< -o $@ $(LDFLAGS)

ASM_TESTS =                                                                    \
    bal                                                                        \
    cksm                                                                       \
    clm                                                                        \
    exrl-ssm-early                                                             \
    icm                                                                        \
    sam                                                                        \
    lpsw                                                                       \
    lpswe-early                                                                \
    lra                                                                        \
    mc                                                                         \
    ssm-early                                                                  \
    stosm-early                                                                \
    unaligned-lowcore

include $(S390X_SRC)/pgm-specification.mak
$(PGM_SPECIFICATION_TESTS): pgm-specification-softmmu.o
$(PGM_SPECIFICATION_TESTS): LDFLAGS+=pgm-specification-softmmu.o
TESTS += $(PGM_SPECIFICATION_TESTS)
